# Generated by Django 4.2.7 on 2023-11-23 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ACCOUNT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(max_length=100)),
                ('private_key', models.CharField(max_length=100)),
                ('public_key', models.CharField(max_length=100)),
                ('balance', models.CharField(max_length=100)),
            ],
        ),
    ]
