# Generated by Django 4.2.7 on 2023-11-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='seed',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
